<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $PostCategories
 * @property Doctrine_Collection $PostCategory
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getPostCategories() Returns the current record's "PostCategories" collection
 * @method Doctrine_Collection getPostCategory()   Returns the current record's "PostCategory" collection
 * @method Category            setName()           Sets the current record's "name" value
 * @method Category            setPostCategories() Sets the current record's "PostCategories" collection
 * @method Category            setPostCategory()   Sets the current record's "PostCategory" collection
 * 
 * @package    postit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as PostCategories', array(
             'refClass' => 'PostCategory',
             'local' => 'category_id',
             'foreign' => 'post_id'));

        $this->hasMany('PostCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}