<?php

/**
 * BasePostCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $category_id
 * @property Post $Post
 * @property Category $Category
 * 
 * @method integer      getPostId()      Returns the current record's "post_id" value
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method Post         getPost()        Returns the current record's "Post" value
 * @method Category     getCategory()    Returns the current record's "Category" value
 * @method PostCategory setPostId()      Sets the current record's "post_id" value
 * @method PostCategory setCategoryId()  Sets the current record's "category_id" value
 * @method PostCategory setPost()        Sets the current record's "Post" value
 * @method PostCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    postit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePostCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_category');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}