<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/14 11:18:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=postit',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
