<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/23 13:51:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=postit',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
